/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BubbleSort;

import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class BubsTest {

    Bubs bubbleSort;
    List<Number> subject;

    @Before
    public void setUp() {

        subject = new ArrayList<Number>(){{
            add(2.0);
            add(3.0);
            add(4.0);
            add(1.0);
        }};

        bubbleSort = new Bubs(subject);
    }

    @Test public void testThatSort1Works() {

        bubbleSort.bblSort1();

        assertEquals(1.0, subject.get(0));
        assertEquals(2.0, subject.get(1));
        assertEquals(3.0, subject.get(2));
        assertEquals(4.0, subject.get(3));

    }

    @Test public void testThatSort2Works() {

        bubbleSort.bblSort2();

        assertEquals(1.0, subject.get(0));
        assertEquals(2.0, subject.get(1));
        assertEquals(3.0, subject.get(2));
        assertEquals(4.0, subject.get(3));

    }

    @Test public void testThatSort3Works() {

        bubbleSort.bblSort3();

        assertEquals(1.0, subject.get(0));
        assertEquals(2.0, subject.get(1));
        assertEquals(3.0, subject.get(2));
        assertEquals(4.0, subject.get(3));

    }
}
